#!/usr/bin/perl
# SPDX-License-Identifier: MIT
# Copyright (C) 2026 Yuri Cherio

use strict;
use warnings;
use Fcntl();
use Time::HiRes();
use Getopt::Long qw(:config no_auto_abbrev no_ignore_case bundling pass_through);

Getopt::Long::GetOptions (
	'resource|r=s' => \(my $resource_id), # ID of the resource everyone competes for
	'pid|p=i' => \(my $owner_pid), # process that wants to lease/own the resource
	'dir|d=s' => \(my $queue_dir), # queue & semaphore lock file DIR
	'concurrency|c=i' => \(my $concurrency = 1), # max number of parallel resource owners
	'exclusivity|x=s' => \(my $exclusivity = 'X'), # exclusivity group code/identifier
	'wait|w=f' => \(my $total_wait_sec), # in seconds total wait time for the resource to become available
	'interval|i=f' => \(my $wakeup_interval_sec), # wake up this often to re-check the queue
	'kill|k=s' => \(my $kill_age_spec), # if another owner process is "stuck", TERM it after this many SECONDS
	'expire|e=f' => \(my $expire_age_sec), # resource will be considered automatically unlocked after this period
	'release|R' => \(my $release), # request to release the lock on the resource
	'exit|E=i' => \(my $wait_expire_exit_code), # verbosity level, can be specified multiple times
	'sweep' => \(my $sweep), # list existing semaphores and purge zombies
	'verbose|v+' => \(my $verbose = 0), # verbosity level, can be specified multiple times
	'help|h' => sub { help(); exit(0); } # need help?
);

my $_sep_ = ' '; # queue descriptor field separator: line, pid, started, leased, exclusivity, concurrency, sema_pid, sema_started
my $rx_pid_line = qr/^((\d++)\Q$_sep_\E([\d\.]++)\Q$_sep_\E([\d\.]++)\Q$_sep_\E(\w++)\Q$_sep_\E(\d++)\Q$_sep_\E(\d++)\Q$_sep_\E([\d\.]++))$/m;

$wait_expire_exit_code //= 122;
($wait_expire_exit_code =~ m{^\d+$} && $wait_expire_exit_code < 256) || quit(123, "Invalid exit code: $wait_expire_exit_code");
my $internal_err = min($wait_expire_exit_code + 1, 255); # Keep it within the range

$sweep && do { sweep_resource_locks(); exit(0); };

# If user command is specified, launch it upon a successful acquisition of the lease
if (scalar(@ARGV) && $ARGV[0] eq '--') {
	shift(@ARGV); # remove '--' if present
}
if (scalar(@ARGV)) {
	$owner_pid //= $$; # I am the borrower by default
	$resource_id //= do {
		require Digest::SHA; # only load the module when needed
		Digest::SHA::sha256_base64(join(q( ), @ARGV)) =~ tr|/+=|__|rd
	};
	prnt("User command present: ".join(',', @ARGV)."\n") if ($verbose >= 2);
}

# validate resource ID token
($resource_id && $resource_id =~ /^(?=\w)[\w\-]{3,64}+(?<=\w)$/s) ||
	quit($internal_err, "Resource ID must be 3-64 characters long: allowed characters are [a-zA-Z0-9_-]\n");
# validate owner/leassee process ID.
defined($owner_pid) || quit($internal_err, "PID is missing\n");
$owner_pid =~ m{^[1-9]\d*$}s || quit($internal_err, "Invalid PID: $owner_pid\n");

$| = 1; # STDOUT->autoflush(1);

my $signal_spec; # a list of delays and signals: delay[=signal][:delay[=signal]]...

if (!$release) {
	($total_wait_sec //= 0) == 0 || $total_wait_sec >= 0.01 ||
		quit($internal_err, "Wait time can be zero or >= 0.01");

	if (!$total_wait_sec) {
		$wakeup_interval_sec = undef; # no waiting, no waking
	} else {
		$wakeup_interval_sec //= min(30, exp(0.71 * log($total_wait_sec)) * 0.2); # default derived from wait time
		(($wakeup_interval_sec =~ /^(?:\d+\.\d*|\.\d+|\d+)(?:[eE][+-]?\d+)?$/s) &&
			($wakeup_interval_sec >= 0.001)) ||
			quit($internal_err, "Wake up interval must be a floating point number >= 0.001");
	}

	if (defined($kill_age_spec)) {
		# my %known_sigs = eval { require Config; ($Config{sig_name_init} =~ m/"(\w+)(", )/gs) };
		$signal_spec = [];
		my ($age_last, $sig_last) = (-1, 'TERM');
		while ($kill_age_spec =~ m{ (?<=^|:) (\d+(?:[,\.]\d+)?) (?:\=(\w+(?:[-+]\d+)?))? (?=$|:) }xgs) {
			my ($age, $sig) = ($1, $2);
			$age_last < $age || quit($internal_err, "Signal delay intervals must go in ascending order");
			push(@$signal_spec, ($age_last = $age), ($sig_last = uc($sig // $sig_last)));
			# $known_sigs{$sig_last} || quit($internal_err, "Invalid signal: $sig_last");
		}
		scalar(@$signal_spec) || quit($internal_err, "Invalid signal specification");
		prnt("Signal delay intervals: ".join(',', @$signal_spec)."\n") if ($verbose >= 3);
	}

	!defined($expire_age_sec) || $expire_age_sec >= 0 ||
		quit($internal_err, "Expiration time can't be negative");

	($exclusivity =~ /^[A-Za-z]{1,48}+$/s) ||
		quit($internal_err, "Invalid exclusivity flag, allowed 1 to 48 alphabetic characters");

	($concurrency =~ m{^[1-9]\d*$}s) or quit($internal_err, "Concurency must be a positive whole number");
}

$queue_dir = ensure_lock_dir($queue_dir);

my $queue_file = "$queue_dir/$resource_id.lock"; # Synchronize by resource token
my $request_time_sec = Time::HiRes::time(); # Used to check if wait should give up waiting and just quit

my $res_label = $release ? "release: sema=$$ -r $resource_id -p $owner_pid --que=$queue_file"
	: "queue: sema=$$ -r $resource_id -p $owner_pid --que=$queue_file -x $exclusivity"
		." -c $concurrency"
		.($wakeup_interval_sec ? " -i $wakeup_interval_sec" : '')
		.($total_wait_sec ? " -w $total_wait_sec" : '')
		.(defined($kill_age_spec) ? " -k $kill_age_spec" : '')
		.($verbose ? " -v" x $verbose : '');
prnt("$res_label\n") if ($verbose);

# Gather process information and SELF-validate
my $owner_started = get_pid_started($owner_pid) // 0;
my $sema_started = get_pid_started($$) // quit($internal_err, "ERROR! Semaphore can not detect its PID: $$\n");
quit($internal_err, "Owner PID $owner_pid is not found") if (!$owner_started && !$release);
my $this_entry_text = $release ? '' :
	(join($_sep_, ($owner_pid, $owner_started, 0, $exclusivity, $concurrency, $$, $sema_started)) . "\n");

$SIG{USR1} = 'IGNORE'; # this signal is used to wake up the process from sleep

# wake up signal handler
my $usr1_wake_handler = ($verbose >= 3) ? sub { prnt("Received wake-up (USR1): {$owner_pid/$$}\n") } : sub {};

my $pid_started_cache = {};
my $owner_signalled = {}; # pid => [delay,signal,...]; problem: may accumulate terminated process records

while (1) { # Keep waiting
	my ($sema_wait_left, $sema_lock_result) = (10); # time limit to wait for the queue lock
	my $sema_give_up_deadline_sec = Time::HiRes::time() + $sema_wait_left;
	while (1) { # wait to lock the queue file
		$sema_lock_result = run_synchronized($queue_file, $sema_wait_left + 0.01, sub { revalidate_queue(@_, $this_entry_text); });
		last if $sema_lock_result->{completed};
		(($sema_wait_left = $sema_give_up_deadline_sec - Time::HiRes::time()) > 0) or
			quit($internal_err, "Couldn't lock semaphore queue file: $queue_file");
	}
	$this_entry_text = ''; # this should be done just once
	my $reval_result = $sema_lock_result->{result};

	my ($nap_seconds, $sema_exit_code) = @$reval_result{qw/nap_seconds exit_code/};
	$sema_exit_code //= 0 if $release; # always exit upon release
	prnt("Result: pid={$owner_pid}, exit={".($sema_exit_code//'')."}, nap={".($nap_seconds//'')."} \n") if $verbose >= 2;

	if (defined($sema_exit_code)) {
		if ($sema_exit_code == 0 && scalar(@ARGV)) {
			$sema_exit_code = system(@ARGV);
			if ($sema_exit_code == -1) {
				prnt("Failed to execute: $!\n", *STDERR);
			} elsif ($sema_exit_code & 127) {
				prnt(sprintf "child died with signal %d, %s coredump\n", ($sema_exit_code & 127), ($sema_exit_code & 128) ? 'with' : 'without', *STDERR);
			} else {
				$sema_exit_code >>= 8;
			}
			system($0, '-r', $resource_id, '-p', $owner_pid, '--release');
		}
		exit($sema_exit_code);
	}

	my $current_wait_time = Time::HiRes::time() - $request_time_sec;
	my $remaining_wait_sec = $total_wait_sec - $current_wait_time;
	$nap_seconds = min($nap_seconds, $remaining_wait_sec, $wakeup_interval_sec); # minimum between scheduld nap time and remaining wait time
	prnt("Curr wait time: {$current_wait_time}, left: {$remaining_wait_sec}, next nap: {$nap_seconds} sec, {$owner_pid/$$}\n") if ($verbose >= 2);
	quit($wait_expire_exit_code, "I've been waiting for too long, bye-bye: [$res_label].\n") if ($remaining_wait_sec <= 0);

	{
		local $SIG{USR1} = $usr1_wake_handler; # allow the signal to wake up the process
		Time::HiRes::nanosleep(int($nap_seconds * 1000000000)); # can be awoken by semaphore "release"
	}
}

prnt("Green light for [$res_label]\n") if $verbose;
exit(0);

sub revalidate_queue {
	my ($queue_fhandle, $this_entry_text) = @_; # Semaphore file handle
	quit($internal_err, "Lock file file handle is not initialized") if !defined($queue_fhandle);

	# Read process QUEUE file
	my $queue_text_src = do { local $/; <$queue_fhandle> } . ''; # Slurp the whole queue file
	prnt("Contents read: $queue_text_src") if ($verbose >= 4);

	prnt("New queue line: $this_entry_text") if $this_entry_text && $verbose >= 2;
	# function result affecting variables
	my $queue_text_wrk = $queue_text_src . $this_entry_text;
	my $queue_text_res = '';
	my ($next_nap_seconds, $sema_exit_code, $sema_found_self, $owner_found_self);
	my $release_found; # "release" action specific, flags if it found its owner

	# loop only variables
	my $entries = []; # [semaphore entries] - all from the file
	my $owners = {}; # pid:started -> [owner entries]
	$pid_started_cache = {}; # pid -> [start time] cache

	while ($queue_text_wrk =~ m/$rx_pid_line/g) { # parse the file, first pass
		my ($q_src, $q_pid, $q_started, $q_leased, $q_exclusivity, $q_concurrency, $q_sema_pid, $q_sema_started) = ($1, $2, $3, $4, $5, $6, $7, $8);

		my $q_sema_started_curr = $q_sema_pid ? get_pid_started($q_sema_pid) // 0 : 0; # updated semaphore started timestamp
		if (!$q_sema_started_curr || $q_sema_started_curr ne $q_sema_started) { # semaphore is either gone or PID reused
			($q_sema_pid, $q_sema_started) = (0, 0);
		}

		$sema_found_self |= ($$ == $q_sema_pid);
		$owner_found_self |= ($q_pid == $owner_pid);

		if ($release && $owner_pid == $q_pid) {
			prnt("Marking for release: $q_pid\n") if ($verbose >= 3);
			$release_found = 1;
			$sema_exit_code //= 0;
			wake_up_sema($q_sema_pid); # released
			next;
		}

		my $q_started_curr = get_pid_started($q_pid) // 0; # updated item started timestamp
		if (!$q_started_curr || $q_started_curr ne $q_started) {
			prnt("Owner is gone, skipping: $q_pid\n") if ($verbose >= 2);
			wake_up_sema($q_sema_pid); # missing/terminated owners
			next; # next line - owner is gone anyway
		}

		my $oid = "$q_pid:$q_started"; # unique process identifier which includes PID and start time
		my $entry = { pid => $q_pid, started => $q_started, oid => $oid,
			leased => $q_leased, exclusivity => $q_exclusivity, concurrency => $q_concurrency,
			sema_pid => $q_sema_pid, sema_started => $q_sema_started };
		push(@$entries, $entry);

		my $owner = $owners->{$oid} //= { oid => $oid, leased => $q_leased };
		if ($owner->{leased} > $q_leased && $q_leased) {
			$owner->{leased} = $q_leased; # this applies to all owner PID entries
		}
	}

	# purge terminated process IDs
	for my $signalled_oid (keys %$owner_signalled) {
		if (!$owners->{$signalled_oid}) {
			delete $owner_signalled->{$signalled_oid};
		}
	}

	my $unique_entries = {}; # hash to track duplicate result entries
	my $running_exclusivity; # exclusivity group of the very first entry
	my ($max_lease_cnt, $owner_count) = (10000, 0);

	for my $entry (@$entries) {
		my ($oid, $pid) = @$entry{qw/oid pid/};
		my $owner = $owners->{$oid} // quit($internal_err, "Error! Abnormal state. Owner record not found: $oid\n");

		if ($pid != $owner_pid && $owner->{leased}) { # some other (not me/self) leased
			# check if the lease expired
			if (defined($expire_age_sec)) { # expire leases after a certain time
				my $owner_lease_age = Time::HiRes::time() - $owner->{leased};
				if ($owner_lease_age >= $expire_age_sec) { # invalidate the lease
					prnt("Lease expired, owner=$pid, age=$owner_lease_age\n") if ($verbose >= 2);
					next; # remove the record of this lease
				} else {
					$next_nap_seconds = min($next_nap_seconds, $expire_age_sec - $owner_lease_age);
				}
			}
			# check if the lease needs to be ordered to terminate
			if (defined($signal_spec)) {{ # killing others is allowed
				my $owner_sig_spec = $owner_signalled->{$oid} // $signal_spec; # [age1,SIG1,age2,SIG2...]
				$owner_sig_spec || last; # skip signaling altogether

				my $age_allowance = $owner_sig_spec->[0];
				my $owner_lease_age = Time::HiRes::time() - $owner->{leased};
				my $till_sig = $age_allowance - $owner_lease_age;
				if ($till_sig <= 0) { # owner lease is older than the allowance
					kill(my $sig_name = $owner_sig_spec->[1], $pid);
					prnt("Sending $sig_name to=$pid, age=$owner_lease_age\n") if ($verbose >= 2);
					if (@$owner_sig_spec < 4) { # the last signal was sent
						$owner_signalled->{$oid} = 0;
						$till_sig = 1;
					} else { # more [age,SIG] element pairs left, remove 2 array elements
						$owner_signalled->{$oid} = $owner_sig_spec = [ @$owner_sig_spec[ 2 .. $#$owner_sig_spec ] ];
						$till_sig = min(1, $owner_sig_spec->[0] - $age_allowance); # delay between the two signals
					}
				}
				if ($till_sig > 0) {
					$next_nap_seconds = min($next_nap_seconds, $till_sig);
					prnt("Next check in $next_nap_seconds, next sig=$owner_sig_spec->[1]\n") if ($verbose >= 2);
				}
			}}
		}

		if ($max_lease_cnt != -1) { # adjust maximum lease count
			$owner_count++ if !$owner->{counted}++; # the first time you see the borrower unique count
			$running_exclusivity //= $entry->{exclusivity}; # the very first one
			$max_lease_cnt = min($entry->{concurrency}, $max_lease_cnt); # Consider & respect other items concurrency
			if ($max_lease_cnt < $owner_count || $running_exclusivity ne $entry->{exclusivity}) { # too many already running - keep waiting
				$max_lease_cnt = -1; # no further leases allowed
			}
		}

		if ($max_lease_cnt != -1) { # still has leases available for allocation
			if (!$owner->{leased}) { # make sure a lease is issued to this owner
				$owner->{leased} = Time::HiRes::time();
			}
		} else { # everyone else must wait
			if ($entry->{sema_pid} == $$ && !$owner->{leased}) {
				my $self_sema_wait_time = Time::HiRes::time() - $request_time_sec;
				if ($total_wait_sec <= $self_sema_wait_time) {
					$sema_exit_code //= $wait_expire_exit_code; # I waited too long but the resource is still not available, time to quit
					next; # next line
				}
			}
		}

		my $owner_leased = $owner->{leased};
		my $sema_pid = $entry->{sema_pid};
		if ($owner_leased) {
			if ($pid == $owner_pid) {
				$sema_exit_code //= 0; # successfull exit code
			}
			if ($sema_pid == $$) {
				@$entry{qw/sema_pid sema_started/} = (0, 0); # I am done and ready to exit
			} elsif ($sema_pid && $entry->{leased} != $owner_leased) { # wake another semaphore up
				wake_up_sema($sema_pid);
			}
		} else { # not leased yet
			if (!$sema_pid) { # requesting semaphore is gone so no one is waiting
				prnt("Owner $pid is not leased and its semaphore is gone. Skipping\n") if ($verbose >= 2);
				next;
			}
		}
		$entry->{leased} = $owner_leased;

		my $entry_line = join($_sep_, @$entry{qw/pid started leased exclusivity concurrency sema_pid sema_started/})."\n";
		if (!$unique_entries->{$entry_line}++) { # ignore duplicate entries
			$queue_text_res .= $entry_line;
		}
	}

	$sema_exit_code //= 0 if $release_found;
	$sema_exit_code //= $internal_err if !$sema_found_self; # someone else purged descriptor with this semaphore - quit
	$sema_exit_code //= $internal_err if !$owner_found_self; # someone else purged descriptor with this owner - quit

	# Test if queue CHANGED and save if it changed
	my $queue_changed = $queue_text_res ne $queue_text_src;
	if (!$queue_text_res) { # empty queue
		unlink($queue_file);
		prnt("Semaphore queue ended\n") if ($verbose >= 2);
	} elsif ($queue_changed) {
		prnt("Semaphore queue changed\n") if ($verbose >= 2);
		seek($queue_fhandle, 0, Fcntl::SEEK_SET);
		truncate($queue_fhandle, 0);
		print $queue_fhandle $queue_text_res;
		prnt($queue_text_res) if ($verbose >= 4);
	}

	prnt(sprintf("Queue list changed: %s, exit code: {%s}, nap: {%s}, {%s/%s}\n",
		$queue_changed ? 'Y' : 'N', $sema_exit_code // '', $next_nap_seconds // '', $owner_pid, $$)) if ($verbose >= 2);

	return { exit_code => $sema_exit_code, nap_seconds => $next_nap_seconds } ;
}

sub wake_up_sema {
	$_[0] > 0 && $_[0] != $$ && kill('USR1', $_[0]);
}

sub ensure_lock_dir {
	my ($dir2ensure) = @_;

	if (!$dir2ensure) {
		my $lock_dir_name = 'zemaphore'; # legacy name for compatibility
		my $xdg_runtime_dir = $ENV{XDG_RUNTIME_DIR} // "/run/user/$<";
		my $tmpfs_queue_dir = "$xdg_runtime_dir/$lock_dir_name";
		-d $tmpfs_queue_dir && return $tmpfs_queue_dir;

		# fallback to $HOME/.local/share for compatibility with OS without XDG_RUNTIME_DIR
		my $legacy_dir = ($ENV{XDG_DATA_HOME} // "$ENV{HOME}/.local/share")."/$lock_dir_name";
		-d $legacy_dir && return $legacy_dir;

		if (-d $xdg_runtime_dir) {
			mkdir($tmpfs_queue_dir) or quit($internal_err, "Could not create LOCK directory: $tmpfs_queue_dir\n$!\n");
			return $tmpfs_queue_dir;
		}

		$dir2ensure = $legacy_dir;
	} elsif (-d $dir2ensure) {
		 return -d $dir2ensure;
	}

	require File::Path; # only load the module when needed
	File::Path::make_path($dir2ensure) or quit($internal_err, "Couldn't create LOCK directory: $dir2ensure");
	chmod 0700, $dir2ensure;
	prnt("Created LOCK directory: $dir2ensure\n") if ($verbose);

	return $dir2ensure;
}


sub min {
	my $result;
	for (@_) {
		$result = $_ if defined($_) && (!defined($result) || $_ < $result);
	}
	return $result;
}

sub get_pid_started {
	$_[0] || return;
	exists $pid_started_cache->{$_[0]} && return $pid_started_cache->{$_[0]};
	my $pid_file = "/proc/$_[0]/stat"; # https://man7.org/linux/man-pages/man5/proc_pid_stat.5.html
	sysopen(my $file_handle, $pid_file, Fcntl::O_RDONLY) or return $pid_started_cache->{$_[0]} = undef;
	sysread($file_handle, my $proc_stats, 4096) or return $pid_started_cache->{$_[0]} = undef;
	my $cmd_end_pos = rindex($proc_stats, ')'); # after command line
	my @pid_stats = split(/ /, substr($proc_stats, $cmd_end_pos + 2));
	my ($state, $time_started) = @pid_stats[0, 19]; # original indexes are [2, 21], but we start with the 2nd
	return $pid_started_cache->{$_[0]} = (($state && !($state eq 'Z' || $state eq 'X')) ? $time_started : undef);
}

sub run_synchronized {
	my ($semaphore_file, $timeout, $sub, @args) = @_; # change to hash pointer

	my $sema_result = lock_semaphore($semaphore_file, $timeout);
	return { elapsed => $sema_result->{elapsed} } if (!$sema_result->{completed});

	my $result = eval{ $sub->($sema_result->{handle}, @args) };
	($_ = delete $sema_result->{handle}) && close($_); # release file lock
	#prnt("DEBUG: sema closed $$\n");

	quit($internal_err, $@) if ($@); # re-raise the exception
	return { result => $result, completed => 1 }; # no error
}

sub lock_semaphore {
	my ($sema_file, $timeout) = @_;
	my ($started, $sema_fhandle) = (Time::HiRes::time());

	my $lock_result = eval {
		run_blocking($timeout, sub {
			while (1) {
				sysopen($sema_fhandle, $sema_file, Fcntl::O_RDWR|Fcntl::O_CREAT) or
					quit($internal_err, "Failed to open '$sema_file': $!"); # oh well, we tried
				flock($sema_fhandle, Fcntl::LOCK_EX) or quit($internal_err, "Failed to flock '$sema_file': $!"); # refuse to continue

				# ensure no one renamed, replaced or removed the file while we were waiting for 'flock'
				my $hndl_inode = ([stat($sema_fhandle)])->[1] // 'y';
				my $name_inode = ([stat($sema_file)] // [])->[1] // 'x';
				last if "$hndl_inode" eq "$name_inode"; # the right file is locked

				close($sema_fhandle); # close and try again
			}
		})
	};

	if ($@ || !$lock_result->{completed}) { # there was an error or timed out
		close($sema_fhandle) if defined($sema_fhandle); # release file lock
		quit($internal_err, $@) if ($@);
		$sema_fhandle = undef;
	}

	return { handle => $sema_fhandle, elapsed => Time::HiRes::time() - $started, completed => defined($sema_fhandle) };
}

sub sweep_resource_locks { #
	$queue_dir //= ensure_lock_dir($queue_dir);

	-d $queue_dir || die("Queue dir is missing: $queue_dir\n");
	my $tick_resolution = eval { require POSIX; POSIX::sysconf(&POSIX::_SC_CLK_TCK) };

	print("Queue dir: '$queue_dir'\n") if $verbose; # my $queue_dir_ls_text = `ls -1 $queue_dir`;
	my $queue_dir_files = ls_dir($queue_dir, sub { $_[0] =~ m/\w\.lock$/ } );

	my $ticks_since_boot = get_pid_started($$); # ticks as of now since boot
	for my $qfile (sort @$queue_dir_files) {
		my $qfpath = "$queue_dir/$qfile";
		my $sema_lock_result = run_synchronized($qfpath, 2, sub { # run locked
			my $qhandle = shift;
			my $qtext = do { local $/; <$qhandle> } . '';
			my $qtext_updated = '';
			my ($line_count, $alive_count, $leased_count, $earliest_started) = (0, 0, 0, $ticks_since_boot);
			my $details_text = '';
			while ($qtext =~ m/$rx_pid_line/g) {
				my ($q_line, $q_pid, $q_started, $q_leased, $q_exclusivity, $q_concurrency, $q_sema_pid, $q_sema_started) = ($1, $2, $3, $4, $5, $6, $7, $8);
				$line_count++;
				my $is_alive = $q_started == (get_pid_started($q_pid) // 0); # same start time - still alive
				if ($is_alive) {
					$alive_count++;
					$leased_count++ if $q_leased;
					$earliest_started = $q_started if $q_started < $earliest_started;
					my $pid_live_sec = ($ticks_since_boot - $q_started) / $tick_resolution;
					$details_text .= sprintf("	%s/%s, age: %s sec, leased: %s, concurrency: %s, exclusivity: %s\n",
						$q_pid, $q_sema_pid || '', $pid_live_sec, $q_leased ? 'yes' : 'no', $q_concurrency, $q_exclusivity);
					$qtext_updated .= "$q_line\n";
				} else {
					$details_text .= sprintf("	%s, ZOMBIE\n", $q_pid);
				}
			}
			print(sprintf("%s, items: %s, alive: %s, leased: %s, oldest: %s sec\n",
				$qfile =~ s!^(?:.*?/)?([^/]+)(?:\.\w+)?$!$1!r, $line_count, $alive_count,
				$leased_count, ($ticks_since_boot - $earliest_started) / $tick_resolution)) if $verbose;
			print($details_text) if $verbose && $details_text;

			if (!$qtext_updated) { # empty queue
				prnt("Purging empty $qfile\n") if ($verbose >= 2);
				unlink($qfpath);
			} elsif ($qtext ne $qtext_updated) { # updated content present
				prnt("Semaphore slimmed $qfile\n") if ($verbose >= 2);
				seek($qhandle, 0, Fcntl::SEEK_SET);
				truncate($qhandle, 0);
				print $qhandle $qtext_updated;
			}
		});

	}
}

# An IO operation may hang infinitely; this function allows setting a time limit
sub run_blocking {
	my ($timeout, $sub, @args) = @_;
	my ($started, $alrm_message) = (Time::HiRes::time(), "b00m\n");
	my $result = eval {
		local $SIG{ALRM} = sub { die $alrm_message };
		Time::HiRes::alarm($timeout);
		my $result = $sub->(@args);
		alarm(0); # Cancel alarm
		return $result;
	};

	quit($internal_err, $@) if ($@ && $@ ne $alrm_message);
	return { result => $result, elapsed => Time::HiRes::time() - $started, completed => !$@ };
}

sub prnt {
	my ($msg, $handle) = (@_, *STDOUT);
	my $pfx = $verbose >= 2 ? get_iso_timestamp('HH:mm:ss.SSS', Time::HiRes::time()) . ' ' : '';
	print $handle $pfx . $msg;
}

sub get_iso_timestamp { # get_iso_timestamp('[[YY]YY-MM-DD] [HH:mm[:ss[.SSSSSS]]]' [, [Time::HiRes::]time() | Time::HiRes::gettimeofday() ])
	my ($format, $time) = @_;

	if (ref($time) eq '') {
		$time = $time =~ /^(\d++)(?:\.(\d*))?/ ? [$1, substr(($2 // '') . '000000', 0, 6)] : quit($internal_err, "bad seconds");
	}
	quit($internal_err, 'bad time') if (ref($time) ne 'ARRAY');

	my ($sec, $min, $hour, $mday, $mon, $year, $wday, $yday, $isdst) = localtime($time->[0]);
	#print(join('|', ($micros, $sec, $min, $hour, $mday, $mon, $year)) . "\n");
	my $l_pad = sub {
		my ($val, $len, $ch) = @_;
		my $len_diff = $len - length($val);
		return ($len_diff <= 0 ? '' : $ch x $len_diff) . "$val";
	};

	# 0-Y 2-M 4-D 6-H 8-m 10-s 12-S
	my $result = '';
	while ($format =~ /((.)\2*)/g) { # repeated character
		my ($seq, $seq_char) = ($1, $2);
		$result .= $seq_char eq 'Y' ? substr("0000".($year + 1900), -length($seq))
			: $seq_char eq 'M' ? $l_pad->($mon + 1, length($seq), '0')
			: $seq_char eq 'D' ? $l_pad->($mday, length($seq), '0')
			: $seq_char eq 'd' ? $l_pad->($yday, length($seq), '0')
			: $seq_char eq 'H' ? $l_pad->($hour, length($seq), '0')
			: $seq_char eq 'm' ? $l_pad->($min, length($seq), '0')
			: $seq_char eq 's' ? $l_pad->($sec, length($seq), '0')
			: $seq_char eq 'S' ? substr("000000$time->[1]", -6, length($seq))
			: $seq_char eq 'w' ? $l_pad->($wday, length($seq), '0')
			: $seq;
	}

	return $result;
}

sub ls_dir {
	my ($dir, $check) = @_;
	opendir(my $dir_handle, $dir) || quit($internal_err, "Can not open $dir: $!");
	my @files = ();
	while (defined(my $file = readdir($dir_handle))) {
		utf8::decode($file);
		$check->($file) && push(@files, $file);
	}
	return \@files;
}

sub quit { # prints a message and exits
	my ($exitcode, $msg, $handle) = @_;
	$handle //= $exitcode ? *STDERR : *STDOUT;
	print $handle $msg =~ s/\s*$/\n/sr;
	exit($exitcode) if defined($exitcode);
}

sub cmd_arg {
	my ($arg) = @_;
	my $escaped_arg = $arg =~ s/([\|\;\&\"\'\`\!\$\%\(\)\<\>\s\#\\])/\\$1/grs;
	return length($escaped_arg) != length($arg) && index($arg, "'") == -1 ? "'$arg'" : $escaped_arg;
}

sub help {
	# Embedded man file
	my $man_text = <<'MAN_CONTENTS';
.\" Automatically generated by Pandoc 3.10
.\"
.TH "lease" "1" "June 04, 2026" "Version 1.0.6" "User Commands"
.SH NAME
\f[B]lease\f[R] \- FIFO semaphore utility that manages resource
ownership by processes.
.SH SYNOPSIS
\f[B]lease\f[R] [\f[I]options\f[R]]...
.PP
\f[B]lease\f[R] [\f[I]options\f[R]]...
\-\- command [\f[I]arguments\&...\f[R]]...
.SH DESCRIPTION
FIFO semaphore utility that manages resource ownership by processes.
.PP
Obtains a lease/ownership for the specified resource.
When the resource lease is requested for a specific PID, it succeeds if
the resource is available, otherwise, it will add the requesting process
to a FIFO queue and block until the resource becomes available when the
other processes that acquired the resource earlier release it or finish
executing.
.PP
A process can borrow a resource either for itself or for another process
by supplying \f[B]\-p PID\f[R].
.PP
This utility can also launch a user\-supplied command upon successful
acquisition of this resource lease.
In this case, option \f[B]\-p\f[R] is not needed and \f[B]\-r\f[R] is
optional and will be calculated, if not specified, by hashing the user
command, thus using the user command as a resource identifier.
.PP
A resource can be explicitly released with the \f[B]\-\-release\f[R]
option.
Otherwise the resource will be released when the owner process ends.
.SH OPTIONS
.TP
\f[B]\-r {resource} | \-\-resource={resource}\f[R]
Resource identifier.
Lease/ownership is created/acquired on this resource.
.TP
\f[B]\-p {PID} | \-\-pid={PID}\f[R]
Process ID that is to become an owner of the resource (to acquire a
lease on it).
.TP
\f[B]\-d {directory} | \-\-dir={directory}\f[R]
A directory where the semaphore/resource/queue files are stored.
Defaults to XDG_RUNTIME_DIR/zemaphore (zemaphore is the legacy name of
the utility) if present, falling back to
XDG_DATA_HOME/.local/share/zemaphore when systemd is not present.
.TP
\f[B]\-c {number} | \-\-concurrency={number}\f[R]
Maximum number of processes allowed to own/lease the resource at the
same time and run concurrently.
.TP
\f[B]\f[R]
Concurrency is enforced within the same concurrency/exclusivity group.
Minimum of 1 is enforced.
Default is 1.
.TP
\f[B]\-x {group} | \-\-exclusivity={group}\f[R]
Exclusivity group code/identifier.
\f[B]\f[R]
.RS
Only processes within one group can be executed concurrently.
Concurrency defines the maximum number of processes that can run in
parallel within the same group.
\f[B]\f[R]
If a resource lease is acquired by Group A then a request from Group B
will block until all processes in Group A scheduled before have
completed and released this resource.
\f[B]\f[R]
Optional, defaults to \f[B]X\f[R]
.RE
.TP
\f[B]\-w {wait sec} | \-\-wait={wait sec}\f[R]
Wait this long (seconds) before giving up on locking/acquiring the
resource.
.TP
\f[B]\f[R]
When wait time exceeds this parameter, the semaphore exits with
non\-zero code.
The script keeps waiting if there are too many other processes
requesting this resource.
.TP
\f[B]\f[R]
Requestors are placed in the queue to wait and get their leases as they
become available in FIFO order.
.TP
\f[B]\f[R]
Defaults to infinite wait.
.TP
\f[B]\-i {interval sec} | \-\-interval={interval sec}\f[R]
While waiting for the resource to be released, the script wakes up
periodically to check whether the resource was released or the previous
owner ceased to exist.
This is a polling/wake\-up interval.
Fractional numbers are allowed.
.TP
\f[B]\f[R]
Optional.
The default is automatically derived from the wait time.
.TP
\f[B]\-k {second} | \-\-kill={second}\f[R]
If another process that owns this resource is \(lqstuck\(rq, becomes a
zombie, or simply has been around for this many seconds, then TERM it.
By default no killing is performed.
Fractional numbers are allowed.
.TP
\f[B]\f[R]
This parameter also supports extended format
\f[B]seconds[=SIGNAL][;seconds[=SIGNAL][;\&...]]\f[R].
For example, parameter \f[B]\(lq\-k
300:310:400=INT:410:500=HUP:600=KILL\(rq\f[R] will send \f[B]TERM\f[R]
after 300 and 310 seconds, send \f[B]INT\f[R] at 400 and 410 seconds,
send \f[B]HUP\f[R] at 500 seconds, send \f[B]KILL\f[R] at 600 seconds.
.TP
\f[B]\-e {second} | \-\-expire={second}\f[R]
Resource will be considered automatically unlocked when the lease time
exceeds this number of seconds.
The lease gets invalidated and the resource/lease record is purged
afterward.
.TP
\f[B]\-R | \-\-release\f[R]
Makes an attempt to release a previously obtained/leased resource for
the resource/PID combination.
.RS
Semaphore is more efficient when it is released explicitly.
Doing so sends instant notification signals to other semaphores waiting
for this resource to become available.
Otherwise it relies on periodic polling and may wait for as long as
specified with \f[B]\-i\f[R] before checking whether the resource became
available.
.RE
.TP
\f[B]\-E {int} | \-\-exit={int}\f[R]
Custom exit code to return when wait times out and the resource is still
not available.
Default is 122.
This is useful when you need to distinguish between the exit code of the
user command and failure to acquire the lease in time.
Any internal semaphore error will result in an exit code that is an
increment of this, with the default of 123.
.TP
\f[B]\-\-sweep\f[R]
Purge empty queues/resources.
.RS
With \f[B]\-v\f[R], also lists the existing queues and statistics.
.RE
.TP
\f[B]\-v | \-\-verbose\f[R]
Be verbose, think out loud.
Can be specified multiple times to increase verbosity level.
.TP
\f[B]\-h | \-\-help\f[R]
Print this help.
.SH EXAMPLES
.SS Example. Acquire resource lease with concurrency limit
\f[B]\f[R]
.IP
.EX
lease \-r \(aqXYZ\(aq \-p $PPID \-c 2 \-i 30 \-k 240 \-w 600
.EE
.PP
Asks for a lock on resource \f[B]XYZ\f[R] for the caller shell parent
process, allowing one more resource owner (have 2 owners) to have the
lock at the same time.
.PP
While waiting for the lease to become available, re\-checks every 30
seconds.
.PP
Attempts to TERM other processes that held the lock for over 240
seconds.
.PP
Gives up after 10 minutes of waiting.
.SS Example. Escalating signal sequence
\f[B]\f[R]
.IP
.EX
lease \-r \(aqXYZ\(aq \-p \(dq$(ps \-p $$ \-o ppid:1=)\(dq \-c 2 \-i 30 \-k 240:250:260=HUP:270=INT \-w 600
.EE
.PP
Same as the example above, except that if another lease does not become
available, it attempts sending signals to the lease owner:
.PP
\f[B]TERM\f[R] at 240 and 250 seconds
.PD 0
.P
.PD
\f[B]HUP\f[R] at 260 seconds
.PD 0
.P
.PD
\f[B]INT\f[R] at 270 seconds
.SS Example. Expiring stale leases
\f[B]\f[R]
.IP
.EX
lease \-r \(aqXYZ\(aq \-p \(dq$$\(dq \-i 30 \-e 240 \-w 600 || exit 1
.EE
.PP
Attempts to lock resource \f[B]XYZ\f[R] for the calling shell.
.PP
Checks resource availability every 30 seconds while waiting.
.PP
If the lock is not available after 10 minutes (600 seconds), exits the
calling shell script.
.PP
While waiting, invalidates existing leases older than 240 seconds.
.PP
Keep in mind that invalidating a lease does not necessarily make the
resource immediately eligible to be locked, because there may be other
semaphores already waiting in the FIFO queue.
.SH AUTHORS
Yuri Cherio
.SH COPYRIGHT
Copyright (C) 2026 The Utility Project Contributors
.PD 0
.P
.PD
Licensed under the MIT License (SPDX\-License\-Identifier: MIT)
MAN_CONTENTS

	open(my $man_fh, '|-', "man /dev/stdin") or die("Unable to run man: $!\n");
	print $man_fh $man_text;
}
