#!/usr/bin/perl
# SPDX-License-Identifier: 0BSD
# Copyright (C) 2026 Yuri Cherio
#
# Update copyright headers and other dates

use strict;
use warnings;
use Fcntl();
use Cwd();
use Time::Piece();

my $month_names = [qw(January February March April May June July August September October November December)];
my $ts_now = Time::Piece->localtime();

my @files = map { Cwd::abs_path($_) } @ARGV;

my $this_path = Cwd::abs_path($0);
my $project_dir = ($this_path =~ m{^(.*)/[^/]+/[^/]+$}s) ? $1 : die("No project directory found\n");
chdir($project_dir);

my $updated_cnt = process_files(\@files);
if ($updated_cnt) {
	# print("Updated dates & copyright total: $updated_cnt\n");
	exit(1); # indicate that the source file was updated
}

exit(0);

sub process_files {
	my ($file_paths) = @_;
	my $updated_cnt = 0;
	for my $file_path (@$file_paths) {
		$file_path || next;
		-r $file_path || do { print STDERR "$file_path: not found\n"; next; };
		-f _ || next; # skip if not a regular file
		index($file_path, $project_dir) == 0 || # not in the project directory
			do { print STDERR "$file_path: not in $project_dir\n"; next; };
		my $rel_path = "./".substr($file_path, length($project_dir) + 1);
		# print("$rel_path: considering ...\n");
		$updated_cnt += process_file($rel_path) // 0;
	}
	return $updated_cnt;
}

sub process_copyright {
	my ($file) = @_;

	my $ts_fs = $file->{ts_fs} //
		do { print STDERR "$file->{path}: missing mtime\n"; return; };

	my $year = $ts_fs->strftime('%Y') //
		do { print STDERR "$file->{path}: odd ts_fs\n"; return; };

	my $contents = $file->{contents} =~ s{(?<=\n|^)([^\v\w]*Copyright \(C\) (?:\d{4}-)?)\d{4}( \V+)(?=\n)}{$1$year$2}sgr;
	if ($contents ne $file->{contents}) {
		$file->{contents} = $contents;
		return $file->{changed} = 1;
	}
	return 0;
}

sub process_md_tags {
	my ($file) = @_;

	my $ts_fs = $file->{ts_fs} //
		do { print STDERR "$file->{path}: missing mtime\n"; return; };

	my $date = $ts_fs->strftime('%B %d, %Y') //
		do { print STDERR "$file->{path}: odd ts_fs\n"; return; };

	my $contents = $file->{contents} =~ s{^((?:[^#]\V*\n)*?date:)\h*\w+\h+\d\d,\h+\d{4}\h*\n}{$1 $date\n}sr;
	if ($contents ne $file->{contents}) {
		$file->{contents} = $contents;
		return $file->{changed} = 1;
	}
	return 0;
}

sub process_file_pl_sh {
	my ($file) = @_;
	$file->{contents} = read_file($file->{path}) // return;
	process_copyright($file);
}

sub process_file_md {
	my ($file) = @_;
	$file->{contents} = read_file($file->{path}) // return;
	process_copyright($file);
	process_md_tags($file);
}

sub process_file {
	my ($file_path) = @_;

	my $file = get_file_meta($file_path) //
		do { print STDERR "$file_path: Error fetching metadata\n"; return; };

	$file->{git_state} ||
		do { print("$file_path: committed, no changes - skip\n"); return; };

	my $line_one = read_line($file_path) //
		do { print STDERR "$file_path: Error reading first line\n"; return; };

	if ($file_path =~ m{\.md$}si) {
		process_file_md($file);
	} elsif ($line_one =~ m{^#!(?:/usr)?/bin/sh\b}s) {
		process_file_pl_sh($file);
	} elsif ($line_one =~ m{^#!/usr/bin/perl\b}s) {
		process_file_pl_sh($file);
	# } elsif ($file_path =~ m{(?:^|/)LICENSE$}s) {
	# 	process_file_pl_sh($file);
	}

	if ($file->{changed}) {
		print("$file_path: dates & copyright updated\n");
		write_file($file_path, $file->{contents});
		update_mtime($file_path, $file->{ts_fs});
	}
	return $file->{changed};
}

sub update_mtime {
	my ($file_path, $ts) = @_;

	my $epoch_time = $ts->epoch ||
		do { print STDERR "$file_path: failed to get epoch $ts\n"; return; };

	utime($epoch_time, $epoch_time, $file_path) or
		do { print STDERR "$file_path: failed to update mtime: $!\n"; };
}

sub get_file_meta {
	my ($file_path) = @_;

	my $mtime = (stat($file_path))[9] //
		do { print STDERR "Error running stat+mtime on '$file_path': $!\n"; return; };
	my $ts_fs = Time::Piece->localtime($mtime) //
		do { print STDERR "Error, unrecognizable mtime: $mtime\n"; return; };

	my $mtime_git = readpipe(q{git log -1 --format=%cd --date=format:"%s" -- }.cmd_arg($file_path)) =~ m/^(\d+)/s ? $1 : undef;
	my $ts_git = $mtime_git ? Time::Piece->localtime($mtime_git) : undef;
	my $git_status = readpipe("git status --porcelain ".cmd_arg($file_path)) =~ s/\v+//gsr;

	return { path => $file_path, ts_fs => $ts_fs, ts_git => $ts_git, git_state => $git_status ? 1 : 0 };
}

sub read_line {
	my ($file_path) = @_;
	sysopen(my $fh, $file_path, Fcntl::O_RDONLY) or
		do { print STDERR "sysopen error on '$file_path': $!\n"; return; };
	sysread($fh, my $buffer, 1024) or
		do { print STDERR "sysread error on '$file_path': $!\n"; return; };
	# substr($buffer, 0, 1) eq '#' ||
	# 	do { print STDERR "not a script: '$file_path'\n"; return; };
	my $eol_idx = index($buffer, "\n");
	$eol_idx > -1 ? substr($buffer, 0, $eol_idx) : undef
}

sub read_file {
	my ($fname) = @_;
	open(my $fhandle, '<', $fname) or
		do { print STDERR "error reading '$fname': $!\n"; return; };
	do { local $/; <$fhandle> }
}

sub write_file {
	my ($fname, $contents) = @_;
	open(my $file_handle, '>', $fname) or
		die "Couldn't open file for writing ($fname): $!\n";
	print $file_handle $contents;
}

sub cmd_arg {
	my ($arg) = @_;
	my $escaped_arg = $arg =~ s/([\|\;\&\"\'\`\!\$\%\(\)\<\>\s\#\\])/\\$1/grs;
	return length($escaped_arg) != length($arg) && index($arg, "'") == -1 ? "'$arg'" : $escaped_arg;
}
