#!/usr/bin/perl
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Yuri Cherio
#
# Update copyright headers and other dates

use strict;
use warnings;
use Fcntl();
use Cwd();
use Time::Piece();

my $month_names = [qw(January February March April May June July August September October November December)];
my $ts_now = Time::Piece->localtime();

my @files = map { Cwd::abs_path($_) } @ARGV;

my $this_path = Cwd::abs_path($0);
my $project_dir = ($this_path =~ m{^(.*)/[^/]+/[^/]+$}s) ? $1 : die("No project directory found\n");
chdir($project_dir);

my $updated_cnt = process_files(\@files);
if ($updated_cnt) {
	print("Updated: $updated_cnt\n");
	exit(1); # indicate that the source file was updated
}

exit(0);

sub process_files {
	my ($file_paths) = @_;
	my $updated_cnt = 0;
	for my $file_path (@$file_paths) {
		$file_path || next;
		-r $file_path || do { print STDERR "$file_path: not found\n"; next; };
		-f _ || next; # skip if not a regular file
		index($file_path, $project_dir) == 0 || # not in the project directory
			do { print STDERR "$file_path: not in $project_dir\n"; next; };
		my $rel_path = "./".substr($file_path, length($project_dir) + 1);
		# print("$rel_path: considering ...\n");
		$updated_cnt += process_file($rel_path) // 0;
	}
	return $updated_cnt;
}

sub process_file_pl_sh {
	my ($file_path, $state) = @_;
	my $ts_fs = $state->{ts_fs} //
		do { print STDERR "$file_path: missing mtime\n"; return; };

	my $expected_line = "# Copyright (C) ".$ts_fs->strftime('%Y')." Yuri Cherio";

	my $file_contents = read_file($file_path);
	$file_contents =~ m{^(.*?\n)(# Copyright \(C\) \d+\b\V*)(\n.*)$}s ||
		do { print STDERR "$file_path: Error detecting copyright line\n"; return; };

	my ($pre, $found_line, $post) = ($1, $2, $3);
	$found_line eq $expected_line &&
		do { print("$file_path: alreay up-to-date\n"); return; };

	my $replace_line = "# Copyright (C) ".$ts_fs->strftime('%Y')." Yuri Cherio";
	print("$file_path: $found_line -> $replace_line\n");

	write_file($file_path, "$pre$replace_line$post");
	update_mtime($file_path, $ts_fs);

	return 1;
}

sub process_file_md {
	my ($file_path, $state) = @_;
	my $ts_fs = $state->{ts_fs} //
		do { print STDERR "$file_path: missing mtime\n"; return; };

	my $expected_line = "\% ".$ts_fs->strftime('%B %d, %Y');

	my $file_contents = read_file($file_path);
	$file_contents =~ m{^(\%\V+\v+\%\V+\v+)(\% \w+ \d+, \d{4})(\n.*)$}s ||
		do { print STDERR "$file_path: Error detecting date\n"; return; };

	my ($pre, $found_line, $post) = ($1, $2, $3);
	$found_line eq $expected_line &&
		do { print("$file_path: alreay up-to-date\n"); return; };

	my $replace_line = "\% ".$ts_fs->strftime('%B %d, %Y');
	print("$file_path: $found_line -> $replace_line\n");

	write_file($file_path, "$pre$replace_line$post");
	update_mtime($file_path, $ts_fs);

	return 1;
}

sub process_file {
	my ($file_path) = @_;

	my $state = get_file_meta($file_path) //
		do { print STDERR "$file_path: Error fetching metadata\n"; return; };

	$state->{changed} ||
		do { print("$file_path: committed, no changes - skip\n"); return; };

	my $line_one = read_line($file_path) //
		do { print STDERR "$file_path: Error reading first line\n"; return; };

	if ($file_path =~ m{\.md$}si) {
		return process_file_md($file_path, $state);
	} elsif ($line_one =~ m{^#!(?:/usr)?/bin/sh\b}s) {
		return process_file_pl_sh($file_path, $state);
	} elsif ($line_one =~ m{^#!/usr/bin/perl\b}s) {
		return process_file_pl_sh($file_path, $state);
	}

	print("$file_path: not applicable\n");
	undef
}

sub update_mtime {
	my ($file_path, $ts) = @_;

	my $epoch_time = $ts->epoch ||
		do { print STDERR "$file_path: failed to get epoch $ts\n"; return; };

	utime($epoch_time, $epoch_time, $file_path) or
		do { print STDERR "$file_path: failed to update mtime: $!\n"; };
}

sub get_file_meta {
	my ($file_path) = @_;

	my $mtime = (stat($file_path))[9] //
		do { print STDERR "Error running stat+mtime on '$file_path': $!\n"; return; };
	my $ts_fs = Time::Piece->localtime($mtime) //
		do { print STDERR "Error, unrecognizable mtime: $mtime\n"; return; };

	my $mtime_git = readpipe(q{git log -1 --format=%cd --date=format:"%s" -- }.cmd_arg($file_path)) =~ m/^(\d+)/s ? $1 : undef;
	my $ts_git = $mtime_git ? Time::Piece->localtime($mtime_git) : undef;
	my $git_status = readpipe("git status --porcelain ".cmd_arg($file_path)) =~ s/\v+//gsr;
	my $changed = $git_status ? 1 : 0;

	return { ts_fs => $ts_fs, ts_git => $ts_git, changed => $changed };
}

sub read_line {
	my ($file_path) = @_;
	sysopen(my $fh, $file_path, Fcntl::O_RDONLY) or
		do { print STDERR "sysopen error on '$file_path': $!\n"; return; };
	sysread($fh, my $buffer, 1024) or
		do { print STDERR "sysread error on '$file_path': $!\n"; return; };
	# substr($buffer, 0, 1) eq '#' ||
	# 	do { print STDERR "not a script: '$file_path'\n"; return; };
	my $eol_idx = index($buffer, "\n");
	$eol_idx > -1 ? substr($buffer, 0, $eol_idx) : undef
}

sub read_file {
	my ($fname) = @_;
	open(my $fhandle, '<', $fname) or
		die("Couldn't open file ($fname): $!\n");
	do { local $/; <$fhandle> }
}

sub write_file {
	my ($fname, $contents) = @_;
	open(my $file_handle, '>', $fname) or
		die "Couldn't open file for writing ($fname): $!\n";
	print $file_handle $contents;
}

sub cmd_arg {
	my ($arg) = @_;
	my $escaped_arg = $arg =~ s/([\|\;\&\"\'\`\!\$\%\(\)\<\>\s\#\\])/\\$1/grs;
	return length($escaped_arg) != length($arg) && index($arg, "'") == -1 ? "'$arg'" : $escaped_arg;
}
